#!/bin/bash

unlink /usr/bin/iphakethe 2> /dev/null
ln -s /usr/share/iphakethe/iphakethe.py /usr/bin/iphakethe


if [[ -f /etc/cron.d/iphakethe && -f /etc/cron.d/iphakethe.old ]];then
    rm /etc/cron.d/iphakethe
    mv /etc/cron.d/iphakethe.old /etc/cron.d/iphakethe
    chmod 0600 /etc/cron.d/iphakethe
fi

if [[ ! -L /etc/iphakethe ]]; then
	if [[ -d /etc/iphakethe ]];then
		rm -rf /etc/iphakethe	
	fi

	ln -s /usr/share/iphakethe/config/iphakethe /etc/iphakethe 2> /dev/null
fi

if [[ -f /etc/iphakethe/iphakethe.conf ]];then
    mv /etc/iphakethe/iphakethe.conf /etc/iphakethe/iphakethe.conf-dpkg-new
fi

if [[ -f /etc/iphakethe/iphakethe.conf.old ]];then
    mv /etc/iphakethe/iphakethe.conf.old /etc/iphakethe/iphakethe.conf
fi

ln -s /usr/share/iphakethe/apache/iphakethe.conf /etc/apache2/sites-enabled/iphakethe.conf

a2ensite iphakethe.conf
a2enmod cgi